### ISSUE TITLE
failed to get RI price for region and instance type

### ISSUE THREAD

**Issue by tizatron** [Netflix/ice#192]
https://github.com/Netflix/ice/blob/5c76154d3771735618c9bd5c774470e7c3a592e0/src/java/com/netflix/ice/basic/BasicLineItemProcessor.java#L221

Is causing me some grief - mainly because it keeps clogging up my catalina.out file.

Anyone have any insight why I am throwing this error?

**Comment by anpbabaki** [comment]
same here..only on a few instance types.  most of them are the t2 class

**Comment by anpbabaki** [comment]
I narrowed this down to an issue where certain reservation offerings are missing from the  reservation_prices.oneyear.whatever file.

I believe this issue is related to this section in BasicReservationService.java

                    if (offer.getProductDescription().indexOf("Amazon VPC") >= 0)
                        continue;

The code is ignoring any reservation type with "Amazon VPC" in it, probably to avoid duplicates in the the reservation_prices.oneyear.whatever file.  Ths is from the time where AWS instituted VPC's.    Problem is, AWS is phasing out the non Amazon VPC reservation types, so the new instance classes like m4 and t2 are never being added and thereby causing the errors above.  Go into the AWS console and try to purchase a t2 or m4 non Amazon VPC reservation, it will tell you that there are none available.  I changed the code to

                    if (offer.getProductDescription().indexOf("Amazon VPC") < 0)
                     continue;
Now it will take the reservation types WITH "AMazon VPC" in the description, which should take care of all of them.

**Comment by anpbabaki** [comment]
Well now Ive run into another problem with the above change.  All reserved costs are now being rolled up into UpFrontAmortized.

**Comment by anpbabaki** [comment]
OK second issue was occuring because once I changed the filter to get only the VPC RI's, the RI prices for both default and dedicated tenancy being added to the reference file.  I fixed the second issue by filtering out the dedicated RI's

if (offer.getInstanceTenancy().indexOf("default") == -1)
     continue;

**Comment by PabloCastellano** [comment]
After applying these two changes said by @anpbabaki I still get my logs flooded with "failed to get RI price for {region} {instancetype}"

**Comment by CpuID** [comment]
Seeing this issue using 1.1.2 - would love to know how to resolve it. Seeing it for mostly t2, c4 and r4 instances.
